spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl

    username: scott
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    org.hibernate.SQL: debug #log
    org.hibernate.type: trace

mybatis:
  mapper-locations: mapper/*.xml


