server:
  port: 9009

spring:
  datasource:
    url: jdbc:oracle:thin:@rds-dana-prod-db.cyolawjkrdab.ap-southeast-2.rds.amazonaws.com:1521/TKDB
    username: admin
    password: 11111111
    driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    org.hibernate.SQL: debug #log
    org.hibernate.type: trace

mybatis:
  mapper-locations: mapper/*.xml


